### ISSUE TITLE
-0.251 formatted by #,##0.00 strips the minus sign

### ISSUE THREAD

**Issue by marekjalovec** [Fakundo/Excel-Style-Javascript-DataFormatter#2]
simple fix:

replace
`res.value=DataFormatter.fillNumberPattern(parseInt(n[0]),'#{ptrn[1]}')`
with
`res.value=(n[0]!=='-0'?DataFormatter.fillNumberPattern(parseInt(n[0]),'#{ptrn[1]}'):n[0])`

**Comment by fakundo** [comment]
Thank you, I will implement this soon

**Comment by fakundo** [comment]
Done. Thank you for waiting
