### ISSUE TITLE
Webpack and UMD support

### ISSUE THREAD

**Issue by missingdays** [Fakundo/Excel-Style-Javascript-DataFormatter#4]
Hello, and thanks for great library!
But I have problem loading your library in browser using WebPack.

Sample code is the same as in your example

``` javascript
import dataFormatter from 'excel-style-dataformatter';
const result = dataFormatter.format('99', 'Number', 'Currency')
```

Browser logs this

```
index.js:16 Uncaught TypeError: Cannot read property 'format' of undefined
```

index.js:16 is this line

``` javascript
const result = dataFormatter.format(...);
```

So I guess it doesn't import library correctly for some reasong.
In your **webpack.config.js** I noticed that there is no 

``` javascript
output: {
    libraryTarget: 'umd',
    umdNamedDefine: true
}
```

Maybe adding this will fix the problem?

Thanks in advance!

**Comment by fakundo** [comment]
Thank you! Sure, I will fix that soon.
