### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by rissom** [Fakundo/Excel-Style-Javascript-DataFormatter#6]
Hello! 
Thanks for the library. It is very usefull. I have a problem with the localization feature. Maybe it is because I just copied the minified library in my project, but it does not even try to load any of the localization files. The default is "en-US", which is what I wanted, but decimal separator is ",", which is not correct. I fixed my problem by just replacing the value by hand:

```
this.dataFormatter = new DataFormatter({locale : 'en-US'});
this.dataFormatter.locale.decimalSeparator = ".";
this.dataFormatter.locale.thousandSeparator = " ";
```

Any tips or background information, how to use the build in feature? 

Best regards, and again thank you for the library,

Thorsten

**Comment by fakundo** [comment]
Hello! Thank you. I fixed `decimalSeparator` in `en-US.js`. I also separated the localization files. So, take a look at updated README
