### ISSUE TITLE
New version don't support some format

### ISSUE THREAD

**Issue by sergey-spivakov** [Fakundo/Excel-Style-Javascript-DataFormatter#7]
Hi, 

Latest release don't support formatting like this:     #,###,;(#,###,)

I think you need change 
section = section.replace(/(0|#|\?)(\s+)([^0?#]*?)($|\.)/, (a, m1, m2, m3, m4)=> {
to 
section = section.replace(/(0|#|\?)(,+)([^0?#]*?)($|\.)/, (a, m1, m2, m3, m4)=> {

in line 654 src/index.js

Can you check?
Thank you.

**Comment by fakundo** [comment]
Thanks, fixed
